Avatar and alert component created.
ArpitPatni/Component-Library-Arpit_Patni pull request #1
Opened 2022-02-05 21:01 UTC by ArpitPatni

Hi 
I have created avatar and alert component.
Could you please review my code.

2022-02-05 21:38 UTC, anurag-kkumarr commented
Looks good to merge.

2022-02-05 22:03 UTC, vikrantkode requested changes
in Landing Page Ui
- Fix  footer to bottom

2022-02-05 22:03 UTC, vikrantkode commented on Styles/alert.css
> +}
use variable while giving color or background color

2022-02-05 22:03 UTC, vikrantkode commented on Styles/avatar.css
> +.avatar-heading{
Use proper spaces between the classes

2022-02-05 22:03 UTC, vikrantkode commented on Styles/middle.css
> +}
remove commented code if not needed

2022-02-06 16:42 UTC, ArpitPatni commented on Styles/middle.css
> +}
Thank you for suggestion.I have made the changes.

2022-02-06 16:42 UTC, ArpitPatni commented on Styles/avatar.css
> +.avatar-heading{
Thank you for suggestion.I have made the changes.

2022-02-06 16:43 UTC, ArpitPatni commented on Styles/alert.css
> +}
I wouldn't be using alert color in other parts of the project and there are so many colors inside alerts component , that's why I have not used variable for them , other than that variables are being used properly.

2022-02-06 17:02 UTC, merged